import Head from "next/head";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ border: "4px solid black", height: "1000px" }}>
        <h1 align="center">Homepage Oye!!!!!!!!!!</h1>
        {console.log(data)}
        {data.items.map((e) => {
          <div>{e}</div>;
        })}
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  let res = await fetch(
    `https://api.github.com/search/repositories?q=dRahul97`
  );

  let data = await res.json();

  return {
    props: {
      data: data,
    },
  };
}
